modules_dir = "artifacts"

[[module]]
    name = "sqlite3"
    mem_pages_count = 100
    logger_enabled = true

[[module]]
    name = "history"
    mem_pages_count = 100
    logger_enabled = true

[[module]]
    name = "user-list"
    mem_pages_count = 100
    logger_enabled = true

